<?php

/**
 * Implements hook_form_alter().
 */
function ckeditor_questionnaire_tokens_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  print_r('woot');
  if ($form_id == "node_book_edit_form"){
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof \Drupal\node\NodeInterface) {
      // You can get nid and anything else you need from the node object.
      $nid = $node->id();
      print_r($node->toArray());
      /*$form['text']['#markup'] = t('Some text.');*/
    }

  }
}