<?php

use Drupal\node\Entity\Node;
use Drupal\webform\Entity\Webform;

/**
 * Implements hook_form_alter().
 */
function ckeditor_questionnaire_tokens_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //  TODO - Need to finish the integration code after we decide on the specific Document content type structure.
  if ($form_id == "node_plan_document_edit_form") {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof \Drupal\node\NodeInterface) {
      // You can get nid and anything else you need from the node object.
      $nid = $node->id();
      // Load the hidden field that has the webform ID.
      $webformid = $node->get('field_questionformid')->value;

      // Load the content containing the webform.
      $questionnaire = Node::load($webformid);

      // Load the referenced entity - the webform we need.
      $referenceWebform = $questionnaire->get('webform')
        ->first()
        ->get('entity')
        ->getTarget()
        ->getValue();
      // Get the webform target id - string variable.
      $webformTargetId = $referenceWebform->id();

      // Load the webform now that we have the target id.
      $questionnaireWebform = Webform::load($webformTargetId);

      // Get the elements of the webform.
      $elements = $questionnaireWebform->getElementsDecoded();
      // Drop the actions.
      if (isset($elements['actions'])){
        unset($elements['actions']);
      }

      $form['#attached']['drupalSettings']['questionTokens'] = $elements;

      // $form[$form_id] = [
      //   '#markup' => '<div id=\'available_tokens\'>Test value 1,Test Value 2,Test Value 3</div>',
      //   '#allowed_tags' => ['div',],
      // ];
    }
  }

}